var hierarchy =
[
    [ "BearWare.AbusePrevention", "struct_bear_ware_1_1_abuse_prevention.html", null ],
    [ "BearWare.WebRTCAudioPreprocessor.GainController2.AdaptiveDigital", "struct_bear_ware_1_1_web_r_t_c_audio_preprocessor_1_1_gain_controller2_1_1_adaptive_digital.html", null ],
    [ "BearWare.AudioBlock", "struct_bear_ware_1_1_audio_block.html", null ],
    [ "BearWare.AudioCodec", "struct_bear_ware_1_1_audio_codec.html", null ],
    [ "BearWare.AudioConfig", "struct_bear_ware_1_1_audio_config.html", null ],
    [ "BearWare.AudioConfigConstants", "struct_bear_ware_1_1_audio_config_constants.html", null ],
    [ "BearWare.AudioFormat", "struct_bear_ware_1_1_audio_format.html", null ],
    [ "BearWare.AudioInputProgress", "struct_bear_ware_1_1_audio_input_progress.html", null ],
    [ "BearWare.AudioPreprocessor", "struct_bear_ware_1_1_audio_preprocessor.html", null ],
    [ "BearWare.BannedUser", "struct_bear_ware_1_1_banned_user.html", null ],
    [ "BearWare.Channel", "struct_bear_ware_1_1_channel.html", null ],
    [ "BearWare.ClientErrorMsg", "struct_bear_ware_1_1_client_error_msg.html", null ],
    [ "BearWare.ClientKeepAlive", "struct_bear_ware_1_1_client_keep_alive.html", null ],
    [ "BearWare.ClientStatistics", "struct_bear_ware_1_1_client_statistics.html", null ],
    [ "BearWare.DesktopInput", "struct_bear_ware_1_1_desktop_input.html", null ],
    [ "BearWare.DesktopInputConstants", "struct_bear_ware_1_1_desktop_input_constants.html", null ],
    [ "BearWare.DesktopWindow", "struct_bear_ware_1_1_desktop_window.html", null ],
    [ "BearWare.WebRTCAudioPreprocessor.EchoCanceller", "struct_bear_ware_1_1_web_r_t_c_audio_preprocessor_1_1_echo_canceller.html", null ],
    [ "BearWare.EncryptionContext", "struct_bear_ware_1_1_encryption_context.html", null ],
    [ "BearWare.FileTransfer", "struct_bear_ware_1_1_file_transfer.html", null ],
    [ "BearWare.WebRTCAudioPreprocessor.GainController2.FixedDigital", "struct_bear_ware_1_1_web_r_t_c_audio_preprocessor_1_1_gain_controller2_1_1_fixed_digital.html", null ],
    [ "BearWare.WebRTCAudioPreprocessor.GainController2", "struct_bear_ware_1_1_web_r_t_c_audio_preprocessor_1_1_gain_controller2.html", null ],
    [ "IDisposable", null, [
      [ "BearWare.TeamTalk5Srv", "class_bear_ware_1_1_team_talk5_srv.html", null ],
      [ "BearWare.TeamTalkBase", "class_bear_ware_1_1_team_talk_base.html", [
        [ "BearWare.TeamTalk5", "class_bear_ware_1_1_team_talk5.html", null ],
        [ "BearWare.TeamTalk5Pro", "class_bear_ware_1_1_team_talk5_pro.html", null ]
      ] ],
      [ "BearWare.TeamTalkSrvBase", "class_bear_ware_1_1_team_talk_srv_base.html", [
        [ "BearWare.TeamTalk5Srv", "class_bear_ware_1_1_team_talk5_srv.html", null ]
      ] ]
    ] ],
    [ "BearWare.JitterConfig", "struct_bear_ware_1_1_jitter_config.html", null ],
    [ "BearWare.MediaFileInfo", "struct_bear_ware_1_1_media_file_info.html", null ],
    [ "BearWare.MediaFilePlayback", "struct_bear_ware_1_1_media_file_playback.html", null ],
    [ "BearWare.WebRTCAudioPreprocessor.NoiseSuppression", "struct_bear_ware_1_1_web_r_t_c_audio_preprocessor_1_1_noise_suppression.html", null ],
    [ "BearWare.OpusCodec", "struct_bear_ware_1_1_opus_codec.html", null ],
    [ "BearWare.OpusConstants", "struct_bear_ware_1_1_opus_constants.html", null ],
    [ "BearWare.WebRTCAudioPreprocessor.Preamplifier", "struct_bear_ware_1_1_web_r_t_c_audio_preprocessor_1_1_preamplifier.html", null ],
    [ "BearWare.RemoteFile", "struct_bear_ware_1_1_remote_file.html", null ],
    [ "BearWare.ServerProperties", "struct_bear_ware_1_1_server_properties.html", null ],
    [ "BearWare.ServerStatistics", "struct_bear_ware_1_1_server_statistics.html", null ],
    [ "BearWare.ShareWindow", "struct_bear_ware_1_1_share_window.html", null ],
    [ "BearWare.SoundDevice", "struct_bear_ware_1_1_sound_device.html", null ],
    [ "BearWare.SoundDeviceConstants", "struct_bear_ware_1_1_sound_device_constants.html", null ],
    [ "BearWare.SoundDeviceEffects", "struct_bear_ware_1_1_sound_device_effects.html", null ],
    [ "BearWare.SoundLevel", "struct_bear_ware_1_1_sound_level.html", null ],
    [ "BearWare.SpeexCodec", "struct_bear_ware_1_1_speex_codec.html", null ],
    [ "BearWare.SpeexConstants", "struct_bear_ware_1_1_speex_constants.html", null ],
    [ "BearWare.SpeexDSP", "struct_bear_ware_1_1_speex_d_s_p.html", null ],
    [ "BearWare.SpeexDSPConstants", "struct_bear_ware_1_1_speex_d_s_p_constants.html", null ],
    [ "BearWare.SpeexVBRCodec", "struct_bear_ware_1_1_speex_v_b_r_codec.html", null ],
    [ "BearWare.TextMessage", "struct_bear_ware_1_1_text_message.html", null ],
    [ "BearWare.TTAudioPreprocessor", "struct_bear_ware_1_1_t_t_audio_preprocessor.html", null ],
    [ "BearWare.TTMessage", "struct_bear_ware_1_1_t_t_message.html", null ],
    [ "BearWare.UnionData", "struct_bear_ware_1_1_union_data.html", null ],
    [ "BearWare.User", "struct_bear_ware_1_1_user.html", null ],
    [ "BearWare.UserAccount", "struct_bear_ware_1_1_user_account.html", null ],
    [ "BearWare.UserStatistics", "struct_bear_ware_1_1_user_statistics.html", null ],
    [ "BearWare.VideoCaptureDevice", "struct_bear_ware_1_1_video_capture_device.html", null ],
    [ "BearWare.VideoCodec", "struct_bear_ware_1_1_video_codec.html", null ],
    [ "BearWare.VideoFormat", "struct_bear_ware_1_1_video_format.html", null ],
    [ "BearWare.VideoFrame", "struct_bear_ware_1_1_video_frame.html", null ],
    [ "BearWare.WebMVP8Codec", "struct_bear_ware_1_1_web_m_v_p8_codec.html", null ],
    [ "BearWare.WebMVP8CodecConstants", "struct_bear_ware_1_1_web_m_v_p8_codec_constants.html", null ],
    [ "BearWare.WebRTCAudioPreprocessor", "struct_bear_ware_1_1_web_r_t_c_audio_preprocessor.html", null ],
    [ "BearWare.WebRTCConstants", "struct_bear_ware_1_1_web_r_t_c_constants.html", null ],
    [ "BearWare.WindowsFirewall", "class_bear_ware_1_1_windows_firewall.html", null ],
    [ "BearWare.WindowsHelper", "class_bear_ware_1_1_windows_helper.html", null ],
    [ "BearWare.WindowsMixer", "class_bear_ware_1_1_windows_mixer.html", null ]
];